### ISSUE TITLE
Message: Failed to save config. Error: Remote repo https://github.com/banklesschick/gov4git-identity-private.git does not exist or banklesschick-testuser does not have rights to view it. From: getDefaultBranch

### ISSUE THREAD

**Issue by banklesschick** [gov4git/desktop-application#40] opened 2023-11-15 23:39 UTC
Hello team,

I've been building some software and have configured and installed git4gov v1.1.15 on my local machine and set up a user known as BanklessDeSci-govbot with an access token to manage it. 

To test out I created a test user but can't seem to get it added as a member in the gov4git desktop app. I double checked and the identity-private.git file for my personal account definitely exists. How do I enable other org members and gov4git to view it then?

Many thanks ahead of time!

[logs_11_15_2023.txt](https://github.com/gov4git/desktop-application/files/13370718/logs_11_15_2023.txt)

**Comment by petar** [comment] 2023-11-16 00:33
@banklesschick We will add multi-user capabilities to the desktop-app in the near future. Until then, if you want to reuse your desktop app as a different user, you must exit the app and erase (or move) its local storage directory which is $HOME/.gov4git

**Comment by dworthen** [comment] 2023-11-21 18:22
Duplicate of #39

**Closed by dworthen** 2023-11-21 18:22 UTC
